// <auto-generated />
using Automat.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Automat.Migrations
{
    [DbContext(typeof(DossierContext))]
    [Migration("20180214111005_initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Automat.Model.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DossierId");

                    b.Property<byte[]>("RowVersion");

                    b.Property<string>("dossierLinkToFiles");

                    b.Property<string>("dossierNummer")
                        .IsRequired();

                    b.Property<string>("dossierStandvanzaken");

                    b.Property<string>("dossierTitel");

                    b.Property<bool>("isGearchiveerd");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("dossiers");
                });

            modelBuilder.Entity("Automat.Model.DossierPersoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DossierPersoonId");

                    b.Property<bool>("IsHoofdklant");

                    b.Property<byte[]>("RowVersion");

                    b.Property<int>("dossierId");

                    b.Property<int>("persoonId");

                    b.HasKey("Id");

                    b.HasIndex("DossierPersoonId");

                    b.ToTable("dossierPersoon");
                });

            modelBuilder.Entity("Automat.Model.Persoon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PersoonId");

                    b.Property<byte[]>("RowVersion");

                    b.Property<string>("departement");

                    b.Property<string>("email");

                    b.Property<string>("naam")
                        .IsRequired();

                    b.Property<string>("organisatie");

                    b.HasKey("Id");

                    b.HasIndex("PersoonId");

                    b.ToTable("personen");
                });

            modelBuilder.Entity("Automat.Model.Dossier", b =>
                {
                    b.HasOne("Automat.Model.Dossier")
                        .WithMany("dossiers")
                        .HasForeignKey("DossierId");
                });

            modelBuilder.Entity("Automat.Model.DossierPersoon", b =>
                {
                    b.HasOne("Automat.Model.DossierPersoon")
                        .WithMany("DossierPersoons")
                        .HasForeignKey("DossierPersoonId");
                });

            modelBuilder.Entity("Automat.Model.Persoon", b =>
                {
                    b.HasOne("Automat.Model.Persoon")
                        .WithMany("personen")
                        .HasForeignKey("PersoonId");
                });
#pragma warning restore 612, 618
        }
    }
}
